S3 support for phyloseq and TreeSE
jsilve24/philr pull request #17
Opened 2021-07-25 15:07 UTC by antagomir

Opening this PR related to philr issue #16 

All checks pass and this can be reviewed & necessary changes discussed but two things are pending before merge:

- Confirmation that the mia package Bioc devel version has been updated (working on this) as some functionality for `TreeSE` examples is required from there  
- Links in the vignette (between sub-vignettes) may need an update, could not check fully yet

Kindly review and suggest any modifications.

2021-07-29 16:06 UTC, antagomir commented
This PR is now ready. 

Summary of changes:

- Added support for `TreeSummarizedExperiment` and `phyloseq` in the `philr` function via S3 classes

- Revised the vignette to include examples with and without these data formats within a single workflow; we maintain the same workflow than previously; the independent phyloseq and miaverse frameworks can provide additional capabilities for tree handling, ordination, visualization etc. but I aimed to keep things simple and focused on philr functionality in this vignette.

- Some minor changes added that were requested by Bioconductor checks 

After merging, this should be bumped to Bioc devel.

2021-08-10 01:04 UTC, jsilve24 commented
Just a quick update. This is actively on my radar. Hoping to have this reviewed in the next day or two.

2021-08-10 01:59 UTC, jsilve24 reviewed
Thanks for putting all this together. I think this is a very nice contribution. Overall I just had two comments about adding required dependencies and about changing the default behavior of the philr function. 

Happy to discuss more if you feel strongly on either.

2021-08-10 01:59 UTC, jsilve24 commented on R/philr.R
> +philr <- function(df, tree=NULL, abund_values="counts", sbp=NULL, part.weights='enorm.x.gm.counts', ilr.weights='blw.sqrt', return.all=FALSE) { UseMethod("philr") }
Any particular reason you changed the default weights? While in many cases what you changed to work well, I think these are a poor choice for defaults as they are largely heuristic and change the interpretation of the results. Overall this can be a good thing just not a great choice for the default values. 

Unless there is a particular reason, please revert to "uniform" defaults.

2021-08-10 01:59 UTC, jsilve24 commented on DESCRIPTION
> +    methods,
Could we make these dependencies optional? I am fine adding them to suggests but am hesitant to require new dependencies as many users (e.g., current users) do not need the additional overhead. One reason I like the S3 setup you have so helpful put together is that from a user's perspective it hard to see any missing functionality if packages such as phyloseq or these new summarizedexperiment packages are not present yet the functionality is there for people who want it. Also since it is added to the documentation I think users will be aware that this exists as an option.

2021-08-11 12:38 UTC, antagomir commented on DESCRIPTION
> +    methods,
Agreed, just added those too fast. Moving SE and TreeSE to suggests. 

The methods is added as a new import but I think this was required by Bioc checks and it is a very basic pkg.

2021-08-11 14:01 UTC, antagomir commented
All requested changes implemented, with some bioc stilization. Happy to make further fixes if there is a need.

We could change philr input argument `df` to `x` on the same go if this is desired. Or leave as is.

2021-08-11 14:49 UTC, jsilve24 reviewed
Thanks again for all this work. I think I found one error in the proposed pull -- defaults don't seem to have been changed in the main s3 function, only in the individual methods.
I think this will cause problems.

2021-08-11 14:49 UTC, jsilve24 commented on man/convert_to_long.Rd
This looks to me like the defaults are still alterned. Both `part.weights` and `ilr.weights` should be `"uniform"`
I am guessing this may be a git usage error :) -- acctually on further reading I think that you missed this function
and instead changed the defaults on the methods functions.
also:
I am fine with changing `df` to `x` probably for the best long-term to avoid confusion. (just make sure to change for methods as well
or your going to get some annoying warnings from R CMD check if I remember correctly. )

2021-08-11 14:52 UTC, jsilve24 requested changes

2021-08-11 14:52 UTC, jsilve24 commented on R/philr.R
>  #' philr(df, tr, part.weights='enorm.x.gm.counts',
:CORRECT_PLACE:

2021-08-14 12:30 UTC, antagomir commented on man/convert_to_long.Rd
Ok, I keep the non-uniform cases in examples as these were in the examples already before my PR. I have checked, however, that the philr arguments have "uniform" as the default, as originally.

2021-08-14 13:18 UTC, antagomir commented on R/philr.R
>  #' philr(df, tr, part.weights='enorm.x.gm.counts',
This is @example - and the example was using these options already before the PR.

2021-08-14 13:21 UTC, antagomir commented
I think I have now made all requested changes but if not, let us continue discussion & fixing.

2021-08-14 21:51 UTC, jsilve24 approved these changes

2021-08-14 21:52 UTC, jsilve24 approved these changes

2021-08-14 21:52 UTC, jsilve24 commented
This looks great. Also I think you are correct, my appologies for the confusion regarding the default weights. Thank you for your patience and hard work. Merging now.

2021-08-14 21:53 UTC, merged

2021-08-14 22:30 UTC, antagomir commented
Awesome, thanks - pleasure to contribute to such a great package! The phylofactor is possible next target.

I anticipate that the updates will be also pushed to Bioconductor devel upstream to facilitate further use: I noticed that running the standard check BiocCheck::BiocCheck() generates some more suggested coding style updates. But I expect that those are not mandatory for already accepted packages.